### PR TITLE
Implement CUDA timers in Hologram

### PR DESCRIPTION
**Pull request by charmoniumQ**

### CODE REVIEW

**Review by apache8080 — DISMISSED** [review]

**Comment by mhuzai** [comment]
I forget. Why can't we use the logger in here? Is it because of CUDA 10.2 and C++17 version mismatch? If so, can you add that in a comment?

**Review by mhuzai — COMMENTED** [review]
I forget. Why can't we use the logger in here? Is it because of CUDA 10.2 and C++17 version mismatch? If so, can you add that in a comment?

**Comment by mhuzai** [comment]
I pushed a makefile fix. The rest looks good to me. However, some perf updates (related to deviceSync) haven't been pushed yet. Just wanted to make sure that they will be in a future PR.

**Comment by charmoniumQ** [comment]
I'm not sure what you are referring to. `deviceSync` does not appear anywhere in the old code.

**Comment by mhuzai** [comment]
I used deviceSync as a shorthand for cudaDeviceSynchroniza aka cudaThreadSynchronize. There was unnecessary synchronization that was causing a 1.5x slowdown. There was also a bit of cleanup, some comments, and a memcpy that was added at the end to read back the results.

**Review by apache8080 — APPROVED** [review]

**Comment by mhuzai** [comment]
> I used deviceSync as a shorthand for cudaDeviceSynchroniza aka cudaThreadSynchronize. There was unnecessary synchronization that was causing a 1.5x slowdown. There was also a bit of cleanup, some comments, and a memcpy that was added at the end to read back the results.

@charmoniumQ , I would like to conclude this thread before approving this PR so that the changes to hologram do not get lost.

**Comment by charmoniumQ** [comment]
> > I used deviceSync as a shorthand for cudaDeviceSynchroniza aka cudaThreadSynchronize. There was unnecessary synchronization that was causing a 1.5x slowdown. There was also a bit of cleanup, some comments, and a memcpy that was added at the end to read back the results.
> 
> @charmoniumQ , I would like to conclude this thread before approving this PR so that the changes to hologram do not get lost.

These? https://github.com/ILLIXR/HOTlab/blob/d8801c6aac9ec65d40c11c571fd6e43775513089/C/source/generateHologram.cu#L641

**Comment by mhuzai** [comment]
Those have already been removed by not defining `M_CUDA_DEBUG`. I'm talking about [these](https://github.com/ILLIXR/HOTlab/blob/d8801c6aac9ec65d40c11c571fd6e43775513089/C/source/generateHologram.cu#L897) and [this memcpy](https://github.com/ILLIXR/HOTlab/blob/d8801c6aac9ec65d40c11c571fd6e43775513089/C/source/generateHologram.cu#L940). [This is](https://github.com/ILLIXR/HOTlab/blob/616b09e98d159ed3e6a7f76a287662edc44bd69a/C/source/generateHologram.cu#L890) what they should look like.
But don't worry about it now. I'll make the change in a new PR.

**Review by mhuzai — DISMISSED** [review]

**Review by apache8080 — APPROVED** [review]

**Review by mhuzai — APPROVED** [review]

**Pull request merged**
