### PR TITLE
Auto format code in CI

### LINKED ISSUE #45: Run clang-format
- Deliberate on the format
- Also standardize naming conventions (always use `_m_` for private or never)
- Figure out how to enforce (make part of CI?)

### PR DESCRIPTION
**Pull request by mhuzai**
Automatically runs `clang-format` on PRs. Closes #45.

### CODE REVIEW

**Comment by mhuzai** [comment]
pre-commit.ci autofix

**Comment by mhuzai** [comment]
pre-commit.ci autofix

**Review by charmoniumQ — APPROVED** [review]
This is a no-brainer.

What happens to #288?

**Comment by mhuzai** [comment]
> This is a no-brainer.
> 
> What happens to #288?

#288 will get closed. I'll keep the branch, but the PR is no longer required. When we want to set up `clang-tidy`, we can simply add it to the `pre-commit` config file.

**Review by qinjunj — APPROVED** [review]

**Pull request merged**
