### PR TITLE
Fix memory problems in libspatialaudio, audio_pipeline, and extended_window

### PR DESCRIPTION
**Pull request by charmoniumQ**
Valgrand flags many of these.

### CODE REVIEW

**Comment by mhuzai** [comment]
@charmoniumQ, what is the status of this PR? Does it need to be merged in before the submodules get moved out or can/should it wait?

**Comment by charmoniumQ** [comment]
Coming back to this more than 6 months later, there are four relevant changes:

1. Fix audio pipeline memory leaks: https://github.com/ILLIXR/audio_pipeline/compare/4e7027b5baf91d5e29d73a3eff060491b10cf590...f600dec8bc531928ff9c72604e3ad45a4dc70891
2. Fix common/extended_window.hpp memory leaks: https://github.com/ILLIXR/ILLIXR/pull/112/files#diff-c1f222918af8ba25d523451d3d976b833e649b8567b75a2d79c82bf159058802
3. Introduce the dummy plugin plugin: https://github.com/ILLIXR/ILLIXR/pull/112/files#diff-c2df575c9eb61e83b9c6e71f2e6b63b2adf7b77f2e7fc9d0226bc2ae08b28c9e
4. Fix memory leaks in OpenVINS: https://github.com/ILLIXR/open_vins/compare/50d1d5a2869b8d6bc9a276e984d1a2498c59c077...bbcc64b3d5e4b81d84d3ae93451650789cece11b

We should create a new PR and ditch this one.

**Comment by e3m3** [comment]
> 3. [Introduce the dummy plugin plugin](https://github.com/ILLIXR/ILLIXR/pull/112/files#diff-c2df575c9eb61e83b9c6e71f2e6b63b2adf7b77f2e7fc9d0226bc2ae08b28c9e)

So we want to introduce [dummy](https://github.com/ILLIXR/ILLIXR/pull/250/files#diff-1faae8aeac91d84b3987c6feeb2c58949424902ff151241a7401dfec2c4b1bcb) in a separate PR from the `dummy_integrator`?

**Comment by charmoniumQ** [comment]
Agreed

**Comment by charmoniumQ** [comment]
Thanks @e3m3

**Pull request closed without merging**
