### PR TITLE
Fix `headless.yaml` command argument

### PR DESCRIPTION
**Pull request by K-Wu**
This is a one-liner fix for issue mentioned in #277

### CODE REVIEW

**Review by charmoniumQ — DISMISSED** [review]

**Review by mhuzai — APPROVED** [review]

**Comment by mhuzai** [comment]
@K-Wu, thanks for the fix. Can you please also add your name to CONTRIBUTORS?

**Comment by K-Wu** [comment]
@mhuzai Thank you! I've just done this in the latest commit to this source branch.

**Comment by mhuzai** [comment]
Just one more thing: the contributors list needs to be sorted, so if you could move your name in between Lincoln's and Hengzhi's, that would be great.

**Comment by K-Wu** [comment]
Got it. I just fix the ordering in the new commit.

**Review by mhuzai — APPROVED** [review]

**Review by e3m3 — APPROVED** [review]

**Pull request merged**
