### PR TITLE
Remove warnings and install realsense for ubuntu20.04 directly 

### PR DESCRIPTION
**Pull request by qinjunj**
Intel RealSense now supports binary package installation for Ubuntu 20.04. So I removed the warnings and directly installed the package in the script. I am not sure it supports 21.04. Should I add a message for that?

### CODE REVIEW

**Review by mhuzai — DISMISSED** [review]

**Comment by charmoniumQ** [comment]
Should we leave the warning there? The condition `!(ver == 18.04 || ver == 21.04)` is still scary.

**Comment by mhuzai** [comment]
> Should we leave the warning there? The condition `!(ver == 18.04 || ver == 20.04)` is still scary.

Yeah, let's keep it.

**Comment by mhuzai** [comment]
> > Should we leave the warning there? The condition `!(ver == 18.04 || ver == 20.04)` is still scary.
> 
> Yeah, let's keep it.

@qinjunj, if you could add the warning back like Sam suggested, this PR is good to go.

**Comment by mhuzai** [comment]
Absorbed into #250.

**Pull request closed without merging**
