### PR TITLE
Create ORB SLAM plugin

### PR DESCRIPTION
**Pull request by hungdche**

### CODE REVIEW

**Comment by Boyuan-Tian** [comment]
DBoW2 in the `Thirdparty` folder needs to be compiled first before compiling ORB-SLAM3.
You can copy-paste the code from `build.sh` for DBow2.

**Comment by hungdche** [comment]
> DBoW2 in the `Thirdparty` folder needs to be compiled first before compiling ORB-SLAM3. You can copy-paste the code from `build.sh` for DBow2.

I ran `build.sh` first thing in the Makefile for ORB-SLAM3 (can be found [here](https://github.com/ILLIXR/ORB_SLAM3/blob/9efc0848769ac9e5495493d1eacbcca93d462d91/Makefile#L15)).

**Comment by Boyuan-Tian** [comment]
Yeah I saw that. Not sure if this is an issue particular to my machine, but I had `"recipe for target 'CMakeFiles/DBoW2.dir/all' failed"` when compiling ILLIXR with ORB-SLAM3 from scratch.

It turns out that I need to either run `build.sh` manually ahead of time or compile twice. Looks like the results for DoW2 are not ready when ORB is getting compiled.

Have you tried removing the folder in .cache and compiling again from scratch? I guess you will see the same issue then.

**Comment by hungdche** [comment]
I think the issue with ORB SLAM plugin is that the ORB-SLAM branch in which I created the plugin has not been merged into master yet. So I guess either you change this [line](https://github.com/ILLIXR/ILLIXR/blob/feec978ed711a8b8d68cfd1f34e972200e2d272b/configs/rt_slam_plugins.yaml#L18) to "create-illixr-plugin" or merge the branch into master.

**Comment by Boyuan-Tian** [comment]
I actually faced this issue when testing on the branch named "create-illixr-plugin." in the way you mentioned.
Can you verify that you don't have this issue after completely removing the ORB-SLAM3 folders in .cache and recompiling from scratch?
Or I can test on the other machines when I have a chance.

**Pull request closed without merging**
