### PR TITLE
Fix Monado build with runner

### PR DESCRIPTION
**Pull request by mhuzai**
Building Monado with the runner (command: `./runner.sh configs/monado.yaml`) throws: 

`monado_integration/src/xrt/state_trackers/prober/p_prober.c:803:13: error: 'struct prober_device' has no member named 'illixr'
  return pdev->illixr.path;`

### CODE REVIEW

**Comment by mhuzai** [comment]
@Hyjale , try this branch: issue-119-monado-build.

**Comment by Hyjale** [comment]
Monado (branch: `fix-illixr-compositor`) builds successfully.

**Review by charmoniumQ — APPROVED** [review]

**Review by Hyjale — COMMENTED** [review]
Looks good.

**Review by Hyjale — COMMENTED** [review]
Approved.

**Review by Hyjale — COMMENTED** [review]
Approved part 2.

**Review by apache8080 — APPROVED** [review]

**Pull request merged**
