### PR TITLE
Changed errno assertions to RAC calls

### LINKED ISSUE #284: Remove errno asserts
Monado does not have the type of errno checking that we rely on in ILLIXR, and therefore the errno asserts fail all the time, unless we build Monado in `Release`. This is not ideal in general, and definitely not ideal for profiling (no symbols). I'm thinking that we should only keep the RACs and remove all the asserts. The RACs are sufficient as a debugging aid.

### PR DESCRIPTION
**Pull request by e3m3**
Closes #284.

### CODE REVIEW

**Review by mhuzai — APPROVED** [review]
I had forgotten how many RACs we have in the code. Do we really need that many?

**Comment by e3m3** [comment]
> I had forgotten how many RACs we have in the code. Do we really need that many?

Short answer: No. The assertions replaced by RACs in this PR occasionally did catch new errno's from time to time. We can remove more of the RACs, understanding that the log produced by the remaining triggered RACs will describe errors at a coarser granularity.

**Review by charmoniumQ — APPROVED** [review]

**Comment by mhuzai** [comment]
> 
> 
> > I had forgotten how many RACs we have in the code. Do we really need that many?
> 
> Short answer: No. The assertions replaced by RACs in this PR occasionally did catch new errno's from time to time. We can remove more of the RACs, understanding that the log produced by the remaining triggered RACs will describe errors at a coarser granularity.

I think we discussed this before, but I'm forgetting the exact discussion: how many errors does errno actually catch? Outside of that one audio bug where we weren't checking whether the file was opened properly, has errno helped us at all? Why don't other projects have similar errno checking mechanisms?

**Comment by charmoniumQ** [comment]
If a function calls another function that uses `errno` to indicate errors, it must clear before and test afterwards in order to know if an error happened. All projects do this for the sake of correctness.

But in ILLIXR we even stricter. We basically push the clear up to the last operation that could have set errno. This way, if `errno` is set in the middle of inoccuous code, it always indicates someone forgot to clear it, which might make it easier to identify code that doesn't check for errors, of which there was a lot in ILLIXR. When I set out on this, I didn't know how many functions would be able to set `errno` spuriously (e.g. `errno` of `someFunction()` is only meaningful if it returns non-zero). I think this is why most projects don't do this.

I think we have covered much of the code that doesn't check for errors now, so I am less concerned by that.

My recommendation: If little/no maintenance is required, keep the errno checks and clears. give us the errno "always means something is wrong" property. If it requires effort to maintain or if it spews spurious output, remove them. Unfortunately, this must be a globally consistent choice. While it is possible to have different disciplines in different domains, I do not recommend this.

**Review by mhuzai — APPROVED** [review]

**Review by charmoniumQ — APPROVED** [review]

**Pull request merged**
